services:
  postgres:
    container_name: extra-time
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: extra_time_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
